name: Deploy Next.js static site to GitHub Pages

# 👇 This defines when the workflow runs
on:
  push:
    branches: [ main ]  # Runs automatically when you push to the main branch
  workflow_dispatch:    # Allows you to run it manually from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend  # 👈 Add this
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml  # 👈 Add this

      - name: Verify lockfile
        run: ls -la

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build static site
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/out
